### ISSUE TITLE
Add styling for elements that has `inline-edit-mode`

### ISSUE THREAD

**Issue by odinr** [equinor/fusion-react-components#393]
Add css for cells that cant be added
The hook for creating styles should have a parameter indicating if this should be enabled

```scss
// styles.scss
.inline-edit-cell {
   opacity: var(--inline-edit-cell, 1);
}
```
