### ISSUE TITLE
[ag-grid-styles] set correct color for hover/selected on row

### ISSUE THREAD

**Issue by odinr** [equinor/fusion-react-components#419]
set the color in scss by selector.
```css
.ag-grid-row-hover: {
   background-color: var(--ag-grid-row-hover__background)
}
```

set the variable in the `useStyle`hook 
```ts
root: {
  --ag-grid-row-hover__background: theme.interactive_table.cell.getVar('color')
}
```

also implement all other table color from `theme` (EDS tokens)
